### ISSUE TITLE
SSL architecture makes packaging/installation hard

### ISSUE THREAD

**Issue by nmathewson** [ellzey/libevhtp#13]
Right now, if you want SSL with your libevhtp, you build it normally, and if you want no SSL, you build it with DISABLE_SSL.

But this doesn't work so well when some programs on a system want SSL support and some don't.  Either you need to build two copies of libevhtp (one with ssl and one without), or you need all of your programs to link against openssl whether they actually want SSL support or not.

The usual way to deal with this kind of thing is to stick the ssl support in a separate .a and .so library that programs only need to link when they want SSL support, and add a few callbacks as needed to make it get called as appropriate.

**Comment by adamel** [comment]
The *usual* way to solve this is that SSL is always enabled, unless you are on a strange embedded system that doesn't support shared libraries and want multiple programs linked against libevhtp, in which case I see no problems with building two copies of libevhtp.
