### ISSUE TITLE
Missing return check in evhtp_connection_new

### ISSUE THREAD

**Issue by jnwatson** [ellzey/libevhtp#136]
The return code should be checked for bufferevent_socket_connect.

**Comment by ellzey** [comment]
I found one place `evhtp_connection_ssl_new`; is this what you are speaking of?

**Comment by jnwatson** [comment]
Yes.

**Comment by ellzey** [comment]
OK

**Comment by ellzey** [comment]
Pushed. Please in the future add a little more context around your issues. Makes life easier for everyone.
