### ISSUE TITLE
segmentation fault in test.c

### ISSUE THREAD

**Issue by marcoeg** [ellzey/libevhtp#138]
I am having the test program (test.c) failing with a segmentation fault when using it with SSL and threads enabled. Please let me know if it is safe to use the libevhtp2 branch.

I am running the test as follows:

$ ./test -s digicert-server.pem -t -n 2

and I am using ab to excercise it from another server:

 $ ab -c 10  -n 100 https://myserver.io:8081

Running it with gdb this is the stack trace:

gdb) bt
#0  0x00007ffff7428767 in _int_free (av=0x7ffff7762720, p=0x6919c0, have_lock=0) at malloc.c:4117
#1  0x0000000000408a1d in evhtp_conn_free ()
#2  0x00007ffff7989559 in do_write (bev_ssl=0x7fffe8015cf0, atmost=<optimized out>) at bufferevent_openssl.c:711
#3  0x00007ffff7989999 in consider_writing (bev_ssl=0x7fffe8015cf0) at bufferevent_openssl.c:877
#4  0x00007ffff7b9a4dd in evbuffer_run_callbacks (buffer=0x7fffe8042480, running_deferred=<optimized out>) at buffer.c:500
#5  0x00007ffff7b9da04 in evbuffer_add_buffer (outbuf=0x7fffe8042480, inbuf=0x7fffe804c940) at buffer.c:986
#6  0x00007ffff7ba07a0 in bufferevent_write_buffer (bufev=<optimized out>, buf=<optimized out>) at bufferevent.c:422
#7  0x000000000040920b in evhtp_send_reply ()
#8  0x0000000000403cd8 in test_default_cb ()
#9  0x0000000000407795 in _evhtp_req_parser_fini ()
#10 0x000000000040cd58 in evhtp_parser_run ()
#11 0x0000000000408cbf in _evhtp_conn_readcb ()
#12 0x00007ffff7989bf9 in consider_reading (bev_ssl=0x7fffe8015cf0) at bufferevent_openssl.c:828
#13 consider_reading (bev_ssl=0x7fffe8015cf0) at bufferevent_openssl.c:769
#14 0x00007ffff7989c29 in be_openssl_readeventcb (fd=<optimized out>, what=2, ptr=<optimized out>)
    at bufferevent_openssl.c:941
#15 0x00007ffff7ba9a59 in event_process_active_single_queue (base=0x7fffe8000900, activeq=0x7fffe8000d50, 
    max_to_process=2147483647, endtime=0x0) at event.c:1471
#16 0x00007ffff7baa16f in event_process_active (base=0x7fffe8000900) at event.c:1538
#17 event_base_loop (base=0x7fffe8000900, flags=0) at event.c:1761
#18 0x000000000042eb07 in _evhtp_thr_loop ()
#19 0x00007ffff7770e9a in start_thread (arg=0x7ffff5f4b700) at pthread_create.c:308

**Comment by ellzey** [comment]
Ping @marcoeg

**Comment by ellzey** [comment]
Ping @marcoeg

**Comment by ellzey** [comment]
If this is libevent2.1 beta, I'm closing this ticket. The new method of ssl bufferevents is fucked without setting your bufcerevents to deferred, and I haven't been able to look into it.
