### ISSUE TITLE
abort when using `pause` / `resume`

### ISSUE THREAD

**Issue by tjk** [ellzey/libevhtp#144]
Ran into an issue earlier today that I'd appreciate some feedback on.

When replaying access logs, I noticed that calling `evhtp_request_resume` would set the underlying `req->conn->paused` to 0 without actually re-enabling `EV_READ` on the underlying bufferevent.

After some inspection, I ran across this particular commit: https://github.com/ellzey/libevhtp/commit/2abd5918a3837046f1bf6a748f600d194f5ac2cb.

I'm not certain why `bufferevent_enable` is commented out, but it does seem incorrect that the connection is unpaused even though the re-enabling of the read event doesn't occur until after the `resume_ev` is triggered.

In a quick test, commenting out the "premature" setting of `c->paused` to 0 in `evhtp_connection_resume` fixes this particular replay, but I'd love to know if you recall why that line was added in the first place and whether this would uncover another set of issues or not.

Thanks in advance!

**Comment by ellzey** [comment]
Bump

**Comment by tjk** [comment]
Hm, I don't really remember exactly what the problem was. I'll just close this now.
