### ISSUE TITLE
evthr_pool_stop does not guarantee that thread actually stops

### ISSUE THREAD

**Issue by romange** [ellzey/libevhtp#151]
After successfully calling evthr_pool_stop and then calling evthr_pool_free

i get an error at the line below. Which proves that the thread did not really exit.

if ((recvd = recv(sock, &cmd, sizeof(evthr_cmd_t), 0)) <= 0) {
        pthread_mutex_unlock(&thread->rlock);
        if (errno == EAGAIN) {
            goto end;
        } else {
            fprintf(stderr, "recv failed %d\n", sock);   // ERROR : - I added this line
            goto error;
        }
}

**Comment by ellzey** [comment]
There is a patch in the devil tree to do this better.

On Saturday, December 27, 2014, romange <notifications@github.com> wrote:

> Why not adding wait for the thread to exit in evthr_stop? This would make
> the contract better, imho.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellzey/libevhtp/issues/151#issuecomment-68185441>.
>


-- 
Sent from Gmail Mobile

**Comment by sodabrew** [comment]
+1 for devil's threading.

**Comment by ellzey** [comment]
Stupid autocorrect. But I may rename that branch now.

On Sunday, January 4, 2015, Aaron Stone <notifications@github.com> wrote:

> +1 for devil's threading.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellzey/libevhtp/issues/151#issuecomment-68656470>.
>


-- 
Sent from Gmail Mobile
