### ISSUE TITLE
client side keep alive requests leak memory

### ISSUE THREAD

**Issue by erikarn** [ellzey/libevhtp#153]
Hi,

I'm using libevhtp as a client-side and server-side thing. In client side with keepalive requests I've noticed that the requests leak memory. Ie, if I do this:

* create connection
* create request
* request completes - calls the cb to notify that it's finished
* create new request
* .. etc

then what happens is the second request replaces the first request in evhtp_connection_t but it isn't freed, so it leaks.

If I free the request without setting con->request = NULL then it segfaults soon after - since the connection thinks it still has a request.

It doesn't happen with non-keepalive requests - those get freed by evhtp_connection_free() when it closes.

I've worked around it in my code for now by simply manually setting con->request = NULL and then freeing the request myself, but it'd be nice if we could figure out how to do it as part of libevhtp.

**Comment by adamel** [comment]
A fix is part of my outstanding pull request https://github.com/ellzey/libevhtp/pull/143, commit https://github.com/adamel/libevhtp/commit/ec445f96825fd3272c0f91ba78446f75b68bdf02

**Comment by ellzey** [comment]
All good, thanks!
