### ISSUE TITLE
When using libevhtp as HTTP client, cannot obtain HTTP response code in callback

### ISSUE THREAD

**Issue by OxAA** [ellzey/libevhtp#156]
Subj. There's no way to get HTTP response status code from callback, provided in evhtp_request_new(...).

More precisely - evhtp_request_t::status, which is supposed(?) return HTTP response code, but now it can return only EVHTP_RES_OK or EVHTP_RES_ERROR (and other error conditions, like EVHTP_RES_FATAL or hook return values). So, callback can get request->status with code 200 even if server replied 404 Not Found.

I'd like to propose fix for this (actual response code can be obtained via htparser_get_status() ), but there's a question where this request status code should be assigned or if it's a good idea to store response code in this variable at all.

**Comment by adamel** [comment]
Yes there is. evhtp_request_status() has been available since 2013.

**Comment by OxAA** [comment]
Oh, that's fine. I'm closing this one, but comment on evhtp_request_s::status can be easily misunderstood:
> evhtp_res            status;        /**< The HTTP response code or other error conditions */

**Comment by ellzey** [comment]
Ha, thanks @adamel
