### ISSUE TITLE
post request with content type json

### ISSUE THREAD

**Issue by tusshar1** [ellzey/libevhtp#157]
When the request is sent from the client with "Content-type" = "application/json", the body of the request is not sent to the callback functions due to this check in evhtp.c 

 if (strncasecmp(content_type, "application/x-www-form-urlencoded", 33)) {
return 0;
}

So, I want to know is there any other way of getting the body if the content type is not set to "application/x-www-form-urlencoded". Also, if possible can we remove that check ?

**Comment by adamel** [comment]
The body always is in request->buffer_in

The only callback that is not called if the content type is not application/x-www-form-urlencoded is the parser function for application/x-www-form-urlencoded, so I'm not sure what you think the problem is, but rest assured there isn't one.

**Comment by tusshar1** [comment]
Sorry for the confusion.

What I mean is "req->uri->query_raw" is null if I don't set content-type to application/json. Only when I set content-type to "application/x-www-form-urlencoded" then "req->uri->query_raw" is populated.

**Comment by adamel** [comment]
Ouch. Storing the body in req->uri->query_raw for application/x-www-form-urlencoded is IMNSHO a **bug** in evhtp. req->uri should only store parameters coming from the URI, not from the body.

In any case the correct thing to do when you want to get the raw body is to get it from request->buffer_in

**Comment by tusshar1** [comment]
Thanks Marcus for the suggestion. Reading body from buffer_in worked !!
