### ISSUE TITLE
How to get request, connection stats for a transfer?

### ISSUE THREAD

**Issue by niks3089** [ellzey/libevhtp#159]
I would like to know if there is a way to collect stats after a trasfer. Some of the basic stats are:

1. Transfer time for the request.
2. Total bytes downloaded.
3. Download speed.
4. Connection setup time.

What are some of the available stats that can collected currently?

**Comment by adamel** [comment]
libevhtp does not maintain any statistics, but it's easy to gather your own stats by using appropriate hooks.
