### ISSUE TITLE
Content-Lenght for non-keepalive replies

### ISSUE THREAD

**Issue by ilejn** [ellzey/libevhtp#161]
Hello. I am creating 1.0 server that sends reply of initially unknown size and closes connection. It is not obvious how to prevent setting zero Content-Length if HTTP 1.0 is used.

I still hope that I've missed something and it is possible (please, point out).
Otherwise something like this might be helpful

```
diff --git a/evhtp.c b/evhtp.c
index d51ce5e..19e7a5b 100644
--- a/evhtp.c
+++ b/evhtp.c
@@ -1368,7 +1368,8 @@ _evhtp_create_reply(evhtp_request_t * request, evhtp_res code) {
                                      evhtp_header_new("Content-Type", "text/plain", 0, 0));
         }
     } else {
-        if (!evhtp_header_find(request->headers_out, "Content-Length")) {
+        if (!evhtp_header_find(request->headers_out, "Content-Length")
+          && request->keepalive == 1) {
             const char * chunked = evhtp_header_find(request->headers_out,
                                                      "transfer-encoding");
```

**Comment by tjeezy** [comment]
I'm curious about the comment (and would love a reference):

```
/*
* HTTP/1.0 can be chunked as long as the Content-Length header
* is set to 0
*/
```
-- https://github.com/ellzey/libevhtp/blob/develop/evhtp.c#L3049

But in doing a little research, it doesn't seem like HTTP/1.0 supports chunked encoding like you would like it too (it was added in HTTP/1.1).

**Comment by ilejn** [comment]
Chunked encoding in 1.0 is perfectly strange, but it is not default [at least].

I am asking about standard 1.0 behaviour - connection drop terminates data stream which length is not initially known.
Is it possible by libevhtp?

**Comment by ellzey** [comment]
> I'm curious about the comment (and would love a reference):

I found this somewhere, it may have been a proxy specific thing. I may have been on crack. But it's more likely I was initially conforming to RFC, but found some edge case with clients that CAN do chunked as long as length is 0. 

Will get back.

**Comment by ellzey** [comment]
and I think http 1.0, with your patch, and and unknown response size can have a "keep-alive". Since RFC  for 1.0 says that the server closes the connection after it's finished.

**Comment by ellzey** [comment]
Point is, THERE MUST HAVE BEEN A GOOD REASON FOR THIS!

**Comment by ellzey** [comment]
Yeah this is all screwy.

**Comment by ellzey** [comment]
I removed some of that silly stuff

@ilejn check out https://github.com/ellzey/libevhtp/blob/67ed0bce433655dfeab65b797279dd167b394feb/examples/test_basic.c

**Comment by ellzey** [comment]
in develop now.

**Comment by ilejn** [comment]
Many thanks for the supersonic response and for the fix. Works great for me.
Hope that the change did no bad for any user of the library.

**Comment by ellzey** [comment]
> Hope that the change did no bad for any user of the library. 

Doubtful, as @tjeezy pointed out.
