### ISSUE TITLE
Connection not closed sometimes

### ISSUE THREAD

**Issue by ilejn** [ellzey/libevhtp#164]
Hello.

I use libevhtp to serve REST calls via HTTP 1.0

In my libevent callback triggered by a DB event
I call evhtp_send_reply_start, 
then evhtp_send_reply_body (number of times in different calls)
and eventually evhtp_send_reply_end.

Everything is fine while evhtp_send_reply_end call is preceded by evhtp_send_reply_body.

If it so happened that a N-th callback did not bring any further data and I have to just close the connection, I do evhtp_send_reply_end and connection stalls.

The reason is obvious - the code that cares of closing a connection is called from _evhtp_connection_writecb. But we have nothing to send (everything in sent already) 

My particular problem is solved by tiny change of the way I use libevhtp, but behaviour does not seem  transparent and may mislead users of the library. 
Or may be I missed some hints?

**Comment by ellzey** [comment]
did you forget https://github.com/ellzey/libevhtp/blob/develop/examples/test_basic.c#L20-L22

**Comment by ilejn** [comment]
Nope.

I am sorry that I failed to describe the issue properly (but may be you can reread my initial post - the problem occurs if last _evhtp_connection_writecb call happened before evhtp_send_reply_end) and I create a test case hopefully until Tuesday.

**Comment by ellzey** [comment]
create a test case and I'll understand.

**Comment by ilejn** [comment]
Please, let me know if example

```#include <string>
#include <memory>
#include <evhtp.h>

evhtp_request_t* g_req;

void
one_sec(int, short int, void*)
{
  if (evhtp_request_get_proto(g_req) == EVHTP_PROTO_10)
  {
    evhtp_request_set_keepalive(g_req, 0);
  }
  std::unique_ptr<evbuffer, decltype(&evbuffer_free)>
    buf(evbuffer_new(), evbuffer_free);
  evhtp_send_reply_start(g_req, EVHTP_RES_OK);
  evbuffer_add(buf.get(), "foo\n", 4);
  evhtp_send_reply_body(g_req, buf.get());
}

void
say_sorry()
{
  std::unique_ptr<evbuffer, decltype(&evbuffer_free)>
    buf(evbuffer_new(), evbuffer_free);
  std::string sorry(
    "we need to have write callback called after evhtp_send_reply_end\n");
  evbuffer_add(buf.get(), sorry.c_str(), sorry.length());
  evhtp_send_reply_body(g_req, buf.get());
}


void
two_sec(int, short int, void*)
{
  // say_sorry();
  evhtp_send_reply_end(g_req);
}

void
get(evhtp_request_t* req, void* arg)
{
  g_req = req;

  event_base* base = static_cast<event_base*>(arg);

  struct timeval sec1 = { 1, 0 };
  struct timeval sec2 = { 2, 0 };
  event* ev1 = event_new(base, -1, EV_TIMEOUT, one_sec, base);
  event_add(ev1, &sec1);
  event* ev2 = event_new(base, -1, EV_TIMEOUT, two_sec, base);
  event_add(ev2, &sec2);
}

int
main(int, char**)
{
  std::unique_ptr<evbase_t, decltype(&event_base_free)>
    evbase(event_base_new(), event_base_free);
  
  std::unique_ptr<evhtp_t, decltype(&evhtp_free)>
    htp(evhtp_new(evbase.get(), nullptr), evhtp_free);

  evhtp_set_cb(htp.get(), "/stall/", get, evbase.get());

  evhtp_bind_socket(htp.get(), "0.0.0.0", 8088, 2048);
  event_base_loop(evbase.get(), 0);
}
```

is not verbose enough

**Comment by ilejn** [comment]
We create to callbacks called after a one and two seconds after GET received. In first callback we do *evhtp_send_reply_start* and *evhtp_send_reply_body*. In second (and last) we do *evhtp_send_reply_end*, while *say_sorry* is commented

**Comment by ellzey** [comment]
```C
#include <evhtp.h>

static void
one_sec(int s, short events, void * a) {
    evhtp_request_t * req = a;
    struct evbuffer * buf = evbuffer_new();

    evbuffer_add(buf, "foo\n", 4);
    {
        evhtp_request_set_keepalive(req, 0);
        evhtp_send_reply_start(req, EVHTP_RES_OK);
        evhtp_send_reply_body(req, buf);
    }
    evbuffer_free(buf);
}

static void
two_sec(int s, short events, void * a) {
    evhtp_request_t * req = a;

    evhtp_connection_free(evhtp_request_get_connection(req));
}

static void
get(evhtp_request_t * req, void * arg) {
    struct event_base * evb  = arg;
    struct timeval      sec1 = { 1, 0 };
    struct timeval      sec2 = { 2, 0 };
    struct event      * ev1  = event_new(evb, -1, EV_TIMEOUT, one_sec, req);
    struct event      * ev2  = event_new(evb, -1, EV_TIMEOUT, two_sec, req);


    event_add(ev1, &sec1);
    event_add(ev2, &sec2);
}

int
main(int argc, char ** argv) {
    struct event_base * evb = event_base_new();
    evhtp_t           * htp = evhtp_new(evb, NULL);

    evhtp_set_cb(htp, "/stall/", get, evb);

    evhtp_bind_socket(htp, "0.0.0.0", 8081, 1024);
    event_base_loop(evb, 0);

    return 0;
}
```

Unknown sizes (no chunks) == must close connection after done.

**Comment by ilejn** [comment]
The problem is if evhtp_connection_free called until data is really sent, response would be truncated.
So it might be an option (it is usually better to send incomplete response that to hang forever), but not a perfect one.

**Comment by ilejn** [comment]
Let me try to explain my workflow.

I have an internal DB engine that serves my request and returns response split by parts. Part is a libevent callback from my point of view. 
If everything is done, it is indicated by a special mark. May be together with final part of data, but not necessary.
Receiving a part, I resend it via HTTP 1.0 with the help of libevhtp.
Receiving notification that fetching is done, I want to close HTTP connection, but when everything is sent.

I think that it is more or less common situation and it should be handled without special considerations.
If I use evhtp_send_reply_end to finalize the response, the connection is stalled sometimes.
If I use evhtp_connection_free to finalize the response, it is often truncated. 

Unfortunately I am not able to provide a patch, so closing the ticket might be right decision.

**Comment by ellzey** [comment]
Why do you have to use http 1.0? This type of problem you are running into is exactly why 1.1 was made.

**Comment by ilejn** [comment]
The answer is obvious - because 1.0 is required by my clients.
Agree that 1.1 addresses truncation issues, but the situation is special - response is truncated *inside* server.

Yes, "sending one null byte right before evhtp_send_reply_end" is very similar to what I do.
Thanks.
