### ISSUE TITLE
HTTP client callbacks

### ISSUE THREAD

**Issue by leiwang-plus** [ellzey/libevhtp#170]
From my understandings, the typical code for sending Http request is like this:
```
conn = evhtp_connection_new_dns(...);
conn->thread = inboundRequest->conn->thread;
evhtp_set_hook(&conn->hooks, ...);
evhtp_set_hook(&conn->hooks, ...);
```
The connection is made in evhtp_connection_new_dns. I'm wondering if there are any chances that some events happen before 'evhtp_set_hook's are called, then the corresponding user defined callbacks will never be called.
If that's the situation, how can I handle it? How can I ensure my callbacks are called correctly?

Thanks,
Lei

**Comment by ellzey** [comment]
This might be what you're looking for?

```C
/**
 * @brief creates a lock around callbacks and hooks, allowing for threaded
 * applications to add/remove/modify hooks & callbacks in a thread-safe manner.
 *
 * @param htp
 *
 * @return 0 on success, -1 on error
 */
EVHTP_EXPORT int evhtp_use_callback_locks(evhtp_t * htp);
```

**Comment by ellzey** [comment]
bump bump

**Comment by zbhe** [comment]
hi,
  sorry for waiting. I have built a simple server by python,  when request the server by example/test_client.c , sometimes it  whill crash,  the following is server's source code(you should install flask first: pip install flask ):

from flask import Flask
from flask import request

app = Flask(__name__)
@app.route('/', methods=['GET', 'POST', 'DELETE', 'PUT', 'HEAD'])
def hello_world():
    method = request.method
    if method == 'GET':
        return "GET: Hello World!\n" + str(request.headers) + "\n" + irequest.args.get("what", "what")
    elif method == 'POST':
        return 'POST: Hello World!\n' + request.headers.get("ghluo", "") + "\n" + request.form.get("where", "where")
    else:
        return 'DELETE: Hello World!\n' + request.headers.get("ghluo", "") + "\n" + request.args.get("why", "why")

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=61717, debug=True

**Comment by zbhe** [comment]
sorry for the alignment, I can't attach .py file...

**Comment by ellzey** [comment]
no answer
