### ISSUE TITLE
http client: method POST is aborted

### ISSUE THREAD

**Issue by akalend** [ellzey/libevhtp#171]
I using code from test_client.c for HTTP GET method and it is Ok, but if I use HTTP POST, I have hanj. 

    // some part code from /examples/test_client.c
    evhtp_headers_add_header(request->headers_out,
                             evhtp_header_new("Host", "localhost", 0, 0));
    evhtp_headers_add_header(request->headers_out,
                             evhtp_header_new("User-Agent", "libevhtp", 0, 0));
   
    evhtp_headers_add_header(request->headers_out,
                         evhtp_header_new("Content-Length", "7", 0, 0));
    evhtp_headers_add_header(request->headers_out,
                             evhtp_header_new("Connection", "close", 0, 0));

    evbuffer_add_reference(request->buffer_out, "*****\r\n", 7, NULL, NULL);

    evhtp_make_request(conn, request, htp_method_POST, "/foo");
    
    //evbuffer_drain(request->buffer_out, -1);

    event_base_loop(evbase, 0);
    event_base_free(evbase);
    return 0;

**Comment by akalend** [comment]
the working code:
    int
    evhtp_make_request(evhtp_connection_t * c, evhtp_request_t * r,
                       htp_method meth, const char * uri) {
        evbuf_t * obuf;
        char    * proto;

        obuf       = bufferevent_get_output(c->bev);
        r->conn    = c;
        c->request = r;

        switch (r->proto) {
            case EVHTP_PROTO_10:
                proto = "1.0";
                break;
            case EVHTP_PROTO_11:
            default:
                proto = "1.1";
                break;
        }

        evbuffer_add_printf(obuf, "%s %s HTTP/%s\r\n",
                            htparser_get_methodstr_m(meth), uri, proto);

        evhtp_headers_for_each(r->headers_out, _evhtp_create_headers, obuf);
        evbuffer_add_reference(obuf, "\r\n", 2, NULL, NULL);
        evbuffer_add_buffer(obuf, r->buffer_out);

        return 0;
    }

**Comment by ellzey** [comment]
I don't quite understand what the issue is here. Can you tell me exactly what is going wrong?

**Comment by ellzey** [comment]
ping. closing in 48 hours if no response.

**Comment by ellzey** [comment]
no answer
