### ISSUE TITLE
Build fails on centos 7 for develop branch

### ISSUE THREAD

**Issue by kaustubh-d** [ellzey/libevhtp#173]
Hello, Build fails for me on centos 7 for develop branch, but works if I checkout latest tag "1.2.10".
I have libevent-2.0.22-stable installed.

Here is the trace:
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for strndup
-- Looking for strndup - not found
-- Looking for strnlen
-- Looking for strnlen - not found
-- Looking for include file strings.h
-- Looking for include file strings.h - not found
-- Looking for include file string.h
-- Looking for include file string.h - not found
...
...
-- Check size of unsigned long - failed
CMake Error at /usr/share/cmake/Modules/TestBigEndian.cmake:44 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:84 (TEST_BIG_ENDIAN)

**Comment by ellzey** [comment]
CentOS provides old versions of cmake/libtool/autoconf/automake/bison/flex, just about everything you need to actually compile new or updated projects. 
 
cmake-2.8.4 includes /home/mthomas/cmake-2.8.4/Modules/TestBigEndian.cmake

**Comment by kaustubh-d** [comment]
https://github.com/ellzey/libevhtp/pull/202
