### ISSUE TITLE
Interface to configure event base

### ISSUE THREAD

**Issue by leiwang-plus** [ellzey/libevhtp#174]
It would be great if you can provide interfaces to configure event base when event_base_new is called.
Now I need to hack the code as following to make the timeouts more accurate.
```
    struct event_config *cfg = event_config_new();
    if (cfg) {
        event_config_set_flag(cfg, EVENT_BASE_FLAG_NO_CACHE_TIME);
        thread->evbase = event_base_new_with_config(cfg);
        event_config_free(cfg);
    }
```

**Comment by ellzey** [comment]
I would be happy to accept a patch for this; if you have the time.

**Comment by ellzey** [comment]
Bump: the only place where the user does not control the construction of the event_base is in the threading lib. Is this the case for you?

**Comment by ellzey** [comment]
no answer.
