### ISSUE TITLE
EADDRINUSE when trying to bind IPv4 and IPv6 on same port

### ISSUE THREAD

**Issue by TETYYS** [ellzey/libevhtp#175]
Hello,

When I'm trying to bind to 0.0.0.0 (or :: for IPv6) on same port, I get EADDRINUSE (as provided by errno). I'm trying to bind with `evhtp_bind_socket` to different `evhtp_t`. I tried different `event_base` too, but with no luck. When I try to specify, for example, 0.0.0.0 for IPv4, then ::1 for IPv6 and same port for both, everything works fine (well, not everything, because I don't really want to listen on ::1).

**Comment by ellzey** [comment]
there has been a sudden surge in this exact question, or something along the lines for both libevent and evhtp. It's something that has been getting more attention because, well, ISP's are finally allocating v6 space to customers.

https://github.com/libevent/libevent/issues/263 pointed out an RFC that I never saw, but still, doesn't address the issue in code.

The huge issue is that 0.0.0.0 will fall back to IPv6, which is just silly. 

But try one of your original approaches: two evhtp_t's (you don't need two event_bases's), setup the ipv6 one __first__, so you can set thesocket option `IPV6_V6ONLY`. After this, technically you should be able to bind to the rest of the IPv4 addresses on the same port.

**Comment by rraptorr** [comment]
Happy Eyeballs is client side (and is implemented in every browser at least).

This issue is about server, but it is really an OS specific behavior. On Linux it is controlled by /proc/sys/net/ipv6/bindv6only. Setting it to 1 causes IPv4 and IPv6 to be separate sockets. This can also be controlled with setsockopt (IPV6_V6ONLY option) on per socket basis.

**Comment by ellzey** [comment]
which is what I said:

```
But try one of your original approaches: two evhtp_t's (you don't need two event_bases's), setup the ipv6 one first, so you can set the socket option IPV6_V6ONLY. After this, technically you should be able to bind to the rest of the IPv4 addresses on the same port.
```

**Comment by TETYYS** [comment]
Unfortunately, that doesn't seem to work. I used `evhtp_bind_socket(ev, "ipv6:::", ServerPort, -1)` and then
```
int yes = 1;
setsockopt(evconnlistener_get_fd(ev->server), IPPROTO_IPV6, IPV6_V6ONLY, (void*)&yes, sizeof(yes));
```
. After that, `evhtp_bind_socket(ev, "ipv4:0.0.0.0", ServerPort, -1)` failed.

**Comment by ellzey** [comment]
I'm writing a test case for it now. give me a few.

**Comment by ellzey** [comment]
You have to do it before the bind, I made this quick diff; will have to add an option to enable it in the real world.

```diff
diff --git a/evhtp.c b/evhtp.c
index 3244fc2..b612520 100644
--- a/evhtp.c
+++ b/evhtp.c
@@ -3195,6 +3195,13 @@ evhtp_bind_sockaddr(evhtp_t * htp, struct sockaddr * sa, size_t sin_len, int bac
     setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&on, sizeof(on));
     setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (void *)&on, sizeof(on));

+    if (sa->sa_family == AF_INET6) {
+       int rc;
+
+       rc = setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on));
+       evhtp_errno_assert(rc != -1);
+    }
+
 #if defined SO_REUSEPORT
     if (htp->enable_reuseport) {
         setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, (void *)&on, sizeof(on));
diff --git a/examples/CMakeLists.txt b/examples/CMakeLists.txt
index dc820cb..2db1793 100644
--- a/examples/CMakeLists.txt
+++ b/examples/CMakeLists.txt
@@ -6,6 +6,7 @@ add_executable(test_vhost EXCLUDE_FROM_ALL test_vhost.c)
 add_executable(test_client EXCLUDE_FROM_ALL test_client.c)
 add_executable(test_query EXCLUDE_FROM_ALL test_query.c)
 add_executable(test_perf EXCLUDE_FROM_ALL test_perf.c)
+add_executable(v6_v4 EXCLUDE_FROM_ALL v6_v4.c)

 if (NOT EVHTP_DISABLE_EVTHR)
        add_executable(test_proxy EXCLUDE_FROM_ALL test_proxy.c)
@@ -18,7 +19,8 @@ target_link_libraries(test_vhost  evhtp ${LIBEVHTP_EXTERNAL_LIBS} ${SYS_LIBS})
 target_link_libraries(test_client evhtp ${LIBEVHTP_EXTERNAL_LIBS} ${SYS_LIBS})
 target_link_libraries(test_query  evhtp ${LIBEVHTP_EXTERNAL_LIBS} ${SYS_LIBS})
 target_link_libraries(test_perf   evhtp ${LIBEVHTP_EXTERNAL_LIBS} ${SYS_LIBS})
+target_link_libraries(v6_v4       evhtp ${LIBEVHTP_EXTERNAL_LIBS} ${SYS_LIBS})

-add_dependencies(examples test test_basic test_vhost test_client test_proxy test_query test_perf)
+add_dependencies(examples test test_basic test_vhost test_client test_proxy test_query test_perf v6_v4)


diff --git a/examples/v6_v4.c b/examples/v6_v4.c
new file mode 100644
index 0000000..367c3a7
--- /dev/null
+++ b/examples/v6_v4.c
@@ -0,0 +1,50 @@
+#include <stdio.h>
+#include <stdlib.h>
+#include <string.h>
+#include <stdint.h>
+#include <errno.h>
+#include <assert.h>
+#include <sys/socket.h>
+#include <netinet/in.h>
+#include <sys/socket.h>
+
+#include "evhtp-internal.h"
+#include "evhtp.h"
+
+static void
+_req_cb(evhtp_request_t * req, void * arg) {
+    const char * ver = (const char *)arg;
+
+    evbuffer_add(req->buffer_out, ver, strlen(ver));
+    evhtp_send_reply(req, EVHTP_RES_OK);
+}
+
+int
+main(int argc, char ** argv) {
+    struct event_base * evbase;
+    evhtp_t           * htp_v6;
+    evhtp_t           * htp_v4;
+    int                 rc;
+
+    evbase = event_base_new();
+    evhtp_alloc_assert(evbase);
+
+    htp_v6 = evhtp_new(evbase, NULL);
+    evhtp_alloc_assert(htp_v6);
+
+    htp_v4 = evhtp_new(evbase, NULL);
+    evhtp_alloc_assert(htp_v4);
+
+    evhtp_set_gencb(htp_v6, _req_cb, (void *)"ipv6");
+    evhtp_set_gencb(htp_v4, _req_cb, (void *)"ipv4");
+
+    rc = evhtp_bind_socket(htp_v6, "ipv6:::/128", 9090, 1024);
+    evhtp_errno_assert(rc != -1);
+
+    rc = evhtp_bind_socket(htp_v4, "ipv4:0.0.0.0", 9090, 1024);
+    evhtp_errno_assert(rc != -1);
+
+    event_base_loop(evbase, 0);
+
+    return 0;
+} /* main */
```

**Comment by ellzey** [comment]
now I can fix libevent too

**Comment by TETYYS** [comment]
Thanks, building right ahead and will report if it works. :+1:

**Comment by ellzey** [comment]
> Thanks, building right ahead 

Note this only applies to the current develop branch.

**Comment by TETYYS** [comment]
Works on Debian 8.1 (y) , please push this fix in normal release

**Comment by ellzey** [comment]
well, there's a little more thought that has to go into it. For example, do we want to abstract it out so that the user has no idea they actually have two evhtp_t sitting around, and if so, how do we setup the same hooks and all the good things it does. So that was just a hack to get it working :)

**Comment by TETYYS** [comment]
>the user has no idea they actually have two evhtp_t sitting around
what are you talking about? the user would create two evhtp_t for ipv4 and ipv6 separately, as I do. This fix is just to get rid of mentioned
>The huge issue is that 0.0.0.0 will fall back to IPv6, which is just silly.

**Comment by ellzey** [comment]
you fail to see the point. evhtp can be really super easy to use, or it can get really complex; that's up to the user. you have `evhtp_bind`: simple, and then you have evhtp_bind_sockaddr, not so simple.

You can create simple callbacks using gencb or setcb for specific URIs, regex & globing, semi-simple. Then you can set several types of hooks on the base evhtp_t, per-request, and per-connection. 

Some people don't care about that level of complexity, and that's fine. Sometimes programmers don't want to know what is going on, just so long as it works.

**Comment by TETYYS** [comment]
yea, but how is this related with issue?

**Comment by ellzey** [comment]
I'm not going to take code I wrote specifically as a test case and say "good to go". I have to ponder over it just to cover all my bases. 

Use that test code as a patch and use it, that's up to you. But what is not up to you is how I do development

**Comment by ellzey** [comment]
in develop now.
