### ISSUE TITLE
memory leak on libevhtp?

### ISSUE THREAD

**Issue by liangdong2718** [ellzey/libevhtp#177]
I use valgrind as memory ayalyse tool to check any memory leak in my program，
after use siege to send http request:
siege -c 1000 -r 3
(this command will send http request 3000 times)
follow is part of my result:

==57700== 65,376 bytes in 2,724 blocks are still reachable in loss record 279 of 280
==57700==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==57700==    by 0x6356A06: evmap_io_add (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x63475DE: event_add (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x6352957: be_socket_enable (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x6351D3A: bufferevent_enable (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x4779E0: _evhtp_connection_accept (evhtp.c:2056)
==57700==    by 0x477D34: _evhtp_run_in_thread (evhtp.c:2152)
==57700==    by 0x4800EE: _evthr_read_cmd (evthr.c:83)
==57700==    by 0x6347F23: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x480202: _evthr_loop (evthr.c:128)
==57700==    by 0x7018181: start_thread (pthread_create.c:312)
==57700==    by 0x7B4847C: clone (clone.S:111)

==57700== 49,072 bytes in 3,067 blocks are definitely lost in loss record 277 of 280
==57700==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==57700==    by 0x47871F: evhtp_kvs_new (evhtp.c:2457)
==57700==    by 0x478FC1: evhtp_parse_query_wflags (evhtp.c:2776)
==57700==    by 0x47963B: evhtp_parse_query (evhtp.c:3008)
==57700==    by 0x476B2F: _evhtp_request_parser_fini (evhtp.c:1590)
==57700==    by 0x47C4D3: hook_on_msg_complete_run (htparse.c:291)
==57700==    by 0x47FFE7: htparser_run (htparse.c:2007)
==57700==    by 0x47724F: _evhtp_connection_readcb (evhtp.c:1803)
==57700==    by 0x63527C9: bufferevent_readcb (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x6347F23: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9)
==57700==    by 0x480202: _evthr_loop (evthr.c:128)
==57700==    by 0x7018181: start_thread (pthread_create.c:312)

After read sources code, I believe that if the function evhtp_connection_free was called,
the memory of bev and kvs will be free, so I add an hook like follow:
evhtp_set_hook(&request->conn->hooks, evhtp_hook_on_connection_fini, count_connection_fini, NULL);

static uint16_t count_connection_fini() {
    static int count = 1;
    printf("pause_connection_fini times(%d)\n", count);
    count++;
    return EVHTP_RES_OK;
}

the string print out prove the had been called 3000 times, it looks like that evhtp_connection_free had been called but don't free corresponding data.
So, Is it some memory leak exist on libevhtp or I used it in a wrong way?

**Comment by ellzey** [comment]
oh client stuff, yes, that's probably all kinds of broke; let me check it out.

**Comment by ellzey** [comment]
Ok, I think https://github.com/ellzey/libevhtp/commit/a6b00ccb126e18b4ecc2da4b5556bde6904aed90 fixes the problem. Thanks to @jgli! Feel free to re-open if that is not the case.
