### ISSUE TITLE
Problem with regexp on Ubuntu Linux (BSD, OSX works for me)

### ISSUE THREAD

**Issue by pusateri** [ellzey/libevhtp#178]
I'm using regular expression matching on Ubuntu 15.04 (vivid) and can't find a match during a GET request. Here is the setup code:
evhtp_set_regex_cb(htp, "^/instances/([0-9]+)/interfaces/([0-9]+)/", interface_in_instance_cb, NULL);
evhtp_set_regex_cb(htp, "^/instances/([0-9]+)/interfaces/", interfaces_in_instance_cb, NULL);

But URL request for "/instances/1/interfaces/" returns 404 not found.
Other requests setup without regular expressions work fine on Ubuntu:
evhtp_set_cb(htp, "/hosts/", host_records_cb, NULL);

I tried the packages included with Ubuntu (libevhtp 1.2.9) and grabbed the latest from github.
Using the same code on FreeBSD or MacOSX works fine.

Running through the debugger, _evhtp_callback_find() tries to find a match but never does.

**Comment by pusateri** [comment]
Solved. I never had -lonig when linking. Ubuntu was happy to use the internal regexp() library but it doesn't work. Not sure why. But adding the oniguruma library to the linker fixed it.

**Comment by ellzey** [comment]
> Ubuntu was happy to use the internal regexp() 

Yeah, I found oniguruma to be faster; Also the regex functions on the default library and oniguruma use POSIX expressions, not pcre, so keep that in mind.

> But adding the oniguruma library to the linker fixed it.

yup, by any chance are you compiling as a shared object?

**Comment by ellzey** [comment]
closing due to no response.
