### ISSUE TITLE
HOWTO: build with debugging

### ISSUE THREAD

**Issue by pusateri** [ellzey/libevhtp#179]
It took me a little while to figure out how to turn on debugging with cmake and so I thought I'd document it here and maybe you can add it to the build docs.

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_FLAGS_DEBUG="-DEVHTP_DEBUG=1" -DCMAKE_BUILD_TYPE=Debug ..

Thanks for a great library!

**Comment by ellzey** [comment]
With -DCMAKE_BUILD_TYPE=Debug some of those options should already be in place:

```cmake
if (CMAKE_BUILD_TYPE MATCHES Debug)
    message("                              ${CMAKE_C_FLAGS_DEBUG}")
else(CMAKE_BUILD_TYPE MATCHES Release)
    message("                              ${CMAKE_C_FLAGS_RELEASE}")
endif()
```

And test your stdout with CFLAGS=-DPARSER_DEBUG cmake ..

**Comment by ellzey** [comment]
put it up on the wiki
