### ISSUE TITLE
cmake prints incorrect version (1.2.10 instead of 1.2.11) in master

### ISSUE THREAD

**Issue by tjk** [ellzey/libevhtp#193]
CMakeLists.txt should be the "source of truth"? 

It seems like it might be set up a little better in libevhtp2?

**Comment by ellzey** [comment]
Fixed here; https://github.com/ellzey/libevhtp/releases/tag/1.2.11n

**Comment by tjk** [comment]
Meh, I don't care so much that this is "fixed" -- I was more curious about to have a version in one place to avoid this issue in the future. :rabbit:

**Comment by tjk** [comment]
Yeah, looks like libevhtp2 does it better just because it doesn't even declare the preprocessor macros (even libevhtp 1 doesn't seem to use the macros) -- so this is totally unimportant, carry on.

**Comment by ellzey** [comment]
libevhtp2 was going to be an epic overhaul, learning all of the mistakes over the past, what, 7 years.

**Comment by ellzey** [comment]
Thanks, but it is a problem, I've been in a slump recently, and have just dug myself out of it. Now I'm back at full throttle.
