### ISSUE TITLE
how to gracefully close request client connection within hooks/callbacks

### ISSUE THREAD

**Issue by kaustubh-d** [ellzey/libevhtp#205]
Am not able to find any API in documentation that can help in gracefully closing a client connection from a server while request is in progress, say while reading large request body. I see evhtp_connection_free() but dont feel its safe to call this in the registered callback/hooks called by the framework.

For example say the request body is 50 mb and i have registered a connection hook 'evhtp_hook_on_read' to consume and drain data in my libevhtp based server. For some reason say like disk full, if I have to reject the request using 503 (retry after) response, how can I do it with libevhtp API. I want to close the client connection gracefully in the callback handler so that client do not flood us with more data when we are not able to process current request (after we have already processed say 30% incoming data)

...
evhtp_set_hook(&conn->hooks, evhtp_hook_on_read, (evhtp_hook)process_data, arg);
....

evhtp_res process_data(evhtp_request_t \* req, evbuf_t \* buf, void \* arg) 
{
...
do something
...
we realize that some thing is wrong and want to stop accepting more data on "current request" from client...
I can unregister the hooks, add 503 response, but how to close connection so more data does not
get buffered on server??
...
}

**Comment by kaustubh-d** [comment]
Any inputs on this please?

**Comment by adamel** [comment]
You can't both "stop accepting more data" AND send a 503 response. Either you read and discard all data from the client in your paplication and then send a 503 response, or you simply close the the connection to the client, in which case it receives a connection error and there is no reason to send an HTTP response.

You should be able to do the latter in libevhtp by simply calling `shutdown(req->conn->sock, SHUT_RD);`
