### ISSUE TITLE
How to use SSL with my own context?

### ISSUE THREAD

**Issue by jacobmarble** [ellzey/libevhtp#207]
`evhtp_ssl_init()` is very convenient, but not as flexible as creating my own SSL_CTX. For example, I need to pass in a private key as a string, using `SSL_CTX_use_PrivateKey()` but `evhtp_ssl_cfg_t` doesn't allow this. #28 tried to address this problem.

Is it enough to assign a valid `SSL_CTX` object to `evhtp_t.ssl_ctx` instead of calling `evhtp_ssl_init()`? It looks like `_evhtp_connection_accept` decides whether to use SSL with the simple condition `if (connection->htp->ssl_ctx != NULL)`.

**Comment by jacobmarble** [comment]
After assigning my own SSL_CTX to `evhtp_t.ssl_ctx`, `evhtp_free` double-frees it. Inside `evhtp_free`, there is no explanation for the two calls to `SSL_CTX_free(evhtp->ssl_ctx)`, can anyone comment?

**Comment by jacobmarble** [comment]
The double-free issue is fixed in #208

**Comment by ellzey** [comment]
:+1:
