### ISSUE TITLE
How to treat bug caused by upstream library ?

### ISSUE THREAD

**Issue by boytm** [ellzey/libevhtp#213]
libevent 2.0.22 have a bug that corrupt http header by http body's chunk size.

Should we 
* add a C preprocessor  #error directive to warning user to use another libevent version 

or 

* use a workaround for this libevent version: simply comment function evbuffer_expand() in function _evhtp_create_headers() at evhtp.c ?

the below code always produce a broken http header:
```c

void testcb(evhtp_request_t * req, void * a) {

    evhtp_kvs_add_kv(req->headers_out, evhtp_kv_new("Set-Cookie",
                "yyyyyyyy=xxxxxxxx; path=/; domain=.localhost" ,
                0,
                0));
    evhtp_kvs_add_kv(req->headers_out, evhtp_kv_new("Set-Cookie",
                /* long enough to force evbuffer_expand() add a new chain to evbuffer */
                "geoinfo=YToxNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNv"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "abcdefghijklmnopqrstuvwxyz01234567890abcdefghijklmnopqrstuvwxyz01234567890abcdef"
                "Ojg6ImRtYV9jb2RlIjtpOjA7czo5OiJhcmVhX2NvZGUiO2k6MDt9; expires=Fri, 25-Mar-2016 0"
                "8:50:10 GMT; path=/; domain=.localhost" , 0, 0));
    evhtp_kvs_add_kv(req->headers_out, evhtp_kv_new("Server", "libevhtp" , 0, 0));

    evbuf_t *buf = evbuffer_new();
    evbuffer_add_reference(buf, "Let it go!", 10, NULL, NULL);

    evhtp_send_reply_chunk_start(req, EVHTP_RES_OK);
    evhtp_send_reply_chunk(req, buf);
    evhtp_send_reply_chunk_end(req);
}



```

libevent bug page: https://github.com/libevent/libevent/issues/335

**Comment by ellzey** [comment]
I'm actually not a huge fan of add_reference. But you bring up a good
point, and I don't think this is anything complex. The HTTP parser has
probably hit its own stack size. Should make that configurable.

**Comment by adamel** [comment]
Hmm, read again @ellzey. This is a bug in libevent evbuffer being triggered by libevhtp.  evbuffer_add_reference() in the above example has nothing to do with it. The bug is triggered just the same with evbuffer_add() or evbuffer_add_printf().

**Comment by adamel** [comment]
As I noted in the libevent issue the bug exists in all libevent 2.0 releases and the 2.1 branch, even though it's slightly easier to trigger it in 2.0.22. Not sure libevhtp should bother doing anything.

**Comment by ellzey** [comment]
Didn't you fix it in https://github.com/libevent/libevent/issues/335? :8ball: 

FYI: current evhtp develop has a per-connection buffer cache (optional), which makes me wonder why we (or to be honest, me) uses evbuffers as a crutch for simple memory munging without events associated. Just a waste. 

I mean shit, this ancient crap code https://github.com/ellzey/libmorphine/blob/develop/util/buf.c is a pretty usual method for dynamic allocation without much overhead. Also heap queues like this crap: https://github.com/ellzey/liblz/blob/develop/src/heap/lz_heap.h could be of use too.

**Comment by adamel** [comment]
Yes, hopefully. This libevhtp issue was just @boytm asking if we should try to work around the broken libevent in libevhtp, and I think I vote *no*.

**Comment by boytm** [comment]
bufferevent is built on top of evbuffer. If use own lightweight buffer, the data should always copy from own buffer to evbuffer. This waste a memory copy, though evbuffer is more complex than own buffer.

**Comment by ellzey** [comment]
> bufferevent is built on top of evbuffer 

I'm fairly sure I knew this :). But what I am saying is, I am using evbuffers as lazy allocator. Which is more complex than it needs to be.

The idea would be to use the internal smaller allocator, and for the underlying evbuffer inside the bufferevent can get pre-allocated with the size of the internal allocator.

You can use the function I wrote in libevent add_iovec or something like that. Point being we would only have to make (in most cases) one call to evbuffer_add().

Take that internal allocator, replace the cache I discussed before, use add_ref with that data, and you've removed heaps of instruction execution.

FYI, my "E" key is sticky, so if I'm missing e's... that's why.

**Comment by boytm** [comment]
Understand. I'll close this issue.
