### ISSUE TITLE
how to unset an evhtp_callback_t from evhtp_t after evhtp_set_cb

### ISSUE THREAD

**Issue by zhangzihua** [ellzey/libevhtp#218]
First i use evhtp_set_cb to set callback function on some paths

evhtpcb1 = evhtp_set_cb(htp, path1, cb1, NULL);
evhtpcb2 = evhtp_set_cb(htp, path2, cb2, NULL);

Then i  want unset evhtpcb2
I try to find an api like "evhtp_unset_cb" but i failed.

how to do it 

thanks

**Comment by zhangzihua** [comment]
evhtpcb1  is still useful. only unset evhtpcb2

**Comment by zhangzihua** [comment]
Is anybody there？

**Comment by adamel** [comment]
This is an issue tracker, not a forum.
https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde
