### ISSUE TITLE
Can I call evhtp_connection_free() in http client request cb?

### ISSUE THREAD

**Issue by tangwuquan** [ellzey/libevhtp#220]
For http client, it send a request, and receive a response. Then I want to free memory of connection and request. I call evhtp_connection_free() in http client request cb function, but the program core dump. It seemed that I can't call evhtp_connection_free() in the connection's call-back. Why?
Do you have any suggestion about where to call evhtp_connection_free()?

**Comment by adamel** [comment]
You should not call evhtp_connection_free() - that is done by libevhtp itself when the connection is terminated. You should just call evhtp_request_free() in the client response callback.
