### ISSUE TITLE
not a bug, but a question which doesn’t exists in the documentation

### ISSUE THREAD

**Issue by ytrezq** [ellzey/libevhtp#221]
This something that I couldn’t found.

Is it up to the application that use libevhtp to define sizes for EVHTP_RES_ENTOOLARGE and EVHTP_RES_URITOOLARGE ?

I can’t see anything in the library for handling that. Maybe pointing it out in the documentation would avoid applications that use libevhtp open to denial of serves attacks.

**Comment by adamel** [comment]
evhtp is not and will never be a HTTP server - it is just a library aiding to implement one. The EVHTP_RES_* values are simply known HTTP status codes (see http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml for reference), and the majority of them are not generated by libevhtp itself.
