### ISSUE TITLE
How to stop accepting new http requests?

### ISSUE THREAD

**Issue by vdkale** [ellzey/libevhtp#230]
Hi,
Is there a way to stop accepting new http requests before a call is made to `event_base_loopexit()`?

If `evhtp_unbind_socket()` is called before `event_base_loopexit()`, will it help to achieve above requirement?

Thanks.

**Comment by adamel** [comment]
Yes, that is indeed the correct way. evhtp_unbind_socket() will close the listening socket, so any client trying to connect will get a connection refused.
