### ISSUE TITLE
many time_wait sockets  when i use http 1.0 client

### ISSUE THREAD

**Issue by zhangzihua** [ellzey/libevhtp#231]
when i use apache ab  like this
ab  -T "application/octet-stream" -p x -n 10000000 -c 1000 "http://192.250.107.20:28002/"
there are many time_wait sockets and the server begin slow.

i find some  code  in function _evhtp_connection_writecb : 
`if (c->request->keepalive == 1) {
        ...........
        return;
    } else {
        evhtp_connection_free(c);
        return;
    }`
the server active close socket, 

how can i avoid so many time_wait sockets?

thank you

**Comment by adamel** [comment]
You can't affect the number of time_wait sockets at the server side. See https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux.html

**Comment by zhangzihua** [comment]
Thank you for your relay.
The time_wait sockets made by the server active closing.
So if we delay call evhtp_connection_free(c) , the client will close this link, 
Only if the client do not close the tcp link , we call this function. 
Does this methd work?
