### ISSUE TITLE
a question in function _evthr_read

### ISSUE THREAD

**Issue by zhangzihua** [ellzey/libevhtp#234]
Hi
I have a question about the function _evthr_read:
if the "if" condition is true (maybe one byte is late, and will comming with next cmd), the later commands will be always error.  Will this happen？
thank you.

```
static inline int
_evthr_read(evthr_t * thr, evthr_cmd_t * cmd, evutil_socket_t sock) {
    if (recv(sock, cmd, sizeof(evthr_cmd_t), 0) != sizeof(evthr_cmd_t)) {
        return 0;
    }

    return 1;
}
```

**Comment by adamel** [comment]
This is an issue tracker, not a forum.
https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde
