### ISSUE TITLE
Build and work on windows

### ISSUE THREAD

**Issue by chengjianxi** [ellzey/libevhtp#236]
I build `libevhtp` on Windows, but when used has some `LNK 2019` and `LNK 2001` error.
There is also a very important issue, how to used multithreading.
Does anyone can give a solution?

**Comment by adamel** [comment]
Not unless you provide any information... 
What compiler, what libevhtp version, build command used, complete output of the build command?

**Comment by FateStayNight** [comment]
I build libevhtp used mingw-w64(i686-602.0-posix-dwarf-rt_v5-rev1),
libevhtp version: 1.2.11n
compiler: Visual studio 2015
I got an error `lnk2019 unresolved external symbol _mingw_app_type, This symbol is referenced in the function __wassert` when uesd libevhtp , but i have no idea for it.
i already linked: `legacy_stdio_definitions.lib`, `libgcc.a`, `libmingwex.a`, `libmsvcrt.a`, `libevent.lib`, `libevhtp.a`

**Comment by FateStayNight** [comment]
BTW, how to used multithreading?
how to used `evhtp_use_threads` on windows platform?
