### ISSUE TITLE
how to use evhtp_hook_on_error and evhtp_hook_on_conn_error?

### ISSUE THREAD

**Issue by machelcheng** [ellzey/libevhtp#243]
I would like to know how many kinds of  errors, and how to use them, can you give a use case?

**Comment by machelcheng** [comment]
I want to deal with different errors,but i don't know how many kinds of error status，and how to handle each error

**Comment by adamel** [comment]
As of the current master branch the hooks are called with errtype == -1 when max_body_size is exceeded, and when the underlying bufferevent calls the event callback. In the latter case errtype is passed straight through from libevent. See http://www.wangafu.net/~nickm/libevent-book/Ref6_bufferevent.html for more info.
