### ISSUE TITLE
evhtp_ssl_init Memory Leak

### ISSUE THREAD

**Issue by JohnOhl** [ellzey/libevhtp#79]
The function "int evhtp_ssl_init(evhtp_t * htp, evhtp_ssl_cfg_t * cfg);" allocates an SSL CTX @ line 3208 "htp->ssl_ctx = SSL_CTX_new(SSLv23_server_method());"

This CTX doesn't appear to be be freed in "void evhtp_free(evhtp_t * evhtp)" using "void SSL_CTX_free(SSL_CTX *ctx);" (http://linux.die.net/man/3/ssl_ctx_free)

Please correct me if I'm mistaken, but Valgrind seems to be complaining about this.

Thanks!

**Comment by ellzey** [comment]
This should be fixed:

```C
oid
evhtp_free(evhtp_t * evhtp) {
    evhtp_alias_t * evhtp_alias, * tmp;

    if (evhtp == NULL) {
        return;
    }

#ifndef EVHTP_DISABLE_EVTHR
    if (evhtp->thr_pool) {
        evthr_pool_stop(evhtp->thr_pool);
        evthr_pool_free(evhtp->thr_pool);
    }
#endif

#ifndef EVHTP_DISABLE_SSL
    if (evhtp->ssl_ctx) {
        SSL_CTX_free(evhtp->ssl_ctx);
    }
#endif
```

Flog me if I'm wrong.

**Comment by ellzey** [comment]
no answer, keeping commit made.
