### ISSUE TITLE
evhtp_connection_new's behavior  is confusing

### ISSUE THREAD

**Issue by zhangjing** [ellzey/libevhtp#94]
Hi

I write my program like this:
  conn = evhtp_connection_new(evthr_get_base(front_req->conn->thread), "intf.company.com", 80);
  if (conn != NULL){
    conn->thread = front_req->conn->thread;
    request = evhtp_request_new(web_request_done, web_context);
    evhtp_make_request(conn, request, htp_method_GET, url.c_str());
 }

evhtp_connection_new doesn't return null ,but evhtp_make_request will coredump

If replace "intf.company.com"  to ip address , it works

look into the code , the connection may be freed before evhtp_make_request.

Should evhtp_connection_new support domain name?

Thanks
Jing

**Comment by ellzey** [comment]
```C
/**
 * @brief allocate a new connection
 */
EVHTP_EXPORT evhtp_connection_t * evhtp_connection_new_dns(evbase_t * evbase,
    struct evdns_base * dns_base,
    const char * addr, uint16_t port);
```

This is in current develop.

**Comment by zhangjing** [comment]
Great Job , ellzey :)

**Comment by reasonsolo** [comment]
Is the evhtp_connection_new_dns working well now? I attached my log function to evdns, but found all dns requests got timeout.
